### ISSUE TITLE
vgg16convs.mat ?

### ISSUE THREAD

**Issue by shiyanrubing** [meteorshowers/RCF-pytorch#1]
hello, I  want to know what vgg16convs.mat in your data_loader.py  is.  Generally, we use a pretrained model, that is a vgg16.pth file.  Look forward to your response. Thanks.

**Comment by zHanami** [comment]
I reconstruct the code, which is compatible for .pth or .pkl
**RCF_train.py**
``
  print('Initializing weights...')
  net.apply(weights_init)
  # fine-tune the vgg-base net
  print('Initiative VGG net with the pre_trained model.')
  vgg_weights = torch.load(os.path.join(Root_dir, cfg['basenet_model']))
  print('Loading base network...')
  vgg_weights = net.load_vgg16(vgg_weights)
  net.load_state_dict(vgg_weights, strict=False)
**model.RCF**
``

**Comment by shiyanrubing** [comment]
thank you.

**Comment by meteorshowers** [comment]
it is just a caffe pretrained model on  imagenet,  you can find it in the wed.

**Comment by yuyu2172** [comment]
@meteorshowers 
Can you give us a link to the file `vgg16convs.mat`?

**Comment by weipf8** [comment]
Here is the link: http://www.vlfeat.org/matconvnet/models/fast-rcnn-vgg16-pascal07-dagnn.mat

**Comment by manutom** [comment]
could you please share the evaluate.py
