### ISSUE TITLE
vgg16convs.mat

### ISSUE THREAD

**Issue by sunshineflg** [meteorshowers/RCF-pytorch#10]
这个资源能给个链接？

**Comment by MichaelWei7** [comment]
这个：http://www.vlfeat.org/matconvnet/models/fast-rcnn-vgg16-pascal07-dagnn.mat

**Comment by AishuaiYao** [comment]
> 这个：http://www.vlfeat.org/matconvnet/models/fast-rcnn-vgg16-pascal07-dagnn.mat
我不能在这个文件里加载正确的参数。
这个文件只是mat格式vgg吗，还是RCF的训练后的模型？？？
这个看名字只是为fast rcnn准备额vgg参数啊？？？
