### ISSUE TITLE
 请问train_multi_gpu.py在哪里

### ISSUE THREAD

**Issue by ysix7** [meteorshowers/RCF-pytorch#24]

**Comment by jannctu** [comment]
use train_RCF.py instead of train_multi_gpu.py

**Comment by JXingZhao** [comment]
请问多卡训练怎么做呢

**Comment by meteorshowers** [comment]
不好意思，这个库还未添加，可以参照 我的另一个代码库进行多gpu训练
https://github.com/meteorshowers/X-StereoLab

**Comment by meteorshowers** [comment]
@ysix7 @JXingZhao @jannctu
