### ISSUE TITLE
Can't reproduce the report results

### ISSUE THREAD

**Issue by aobannong** [meteorshowers/RCF-pytorch#37]
Hello, I used your codes to train the RCF, with no changes to the codes, the best ODS I got is 0.778 with single scale, which is far from the model your uploaded. Moreover, the visualization results still have many texture edges, which is also far beyond your visualized examples. I have tried pytorch1.2 and pytorch0.4.1, but still have the same problems. Have your ever met such problems in your reproduction?

**Comment by meteorshowers** [comment]
@aobannong 
Do you use voc+BSDS500 dataset?
Do you use data augmentation?

**Comment by aobannong** [comment]
Yes, I used the data provided in the official implementation, and the best result I got for now is 0.788 with step size 15.

**Comment by zyuanbing** [comment]
@aobannong How do you evaluate your model? It seems that the evaluation file `evaluate.py` is not included in the code.

**Comment by sunshine-ssl** [comment]
请问您在训练时是把BSDS500扩充数据和PASCAL的数据混合起来训练的吗，旋转的数据如何裁剪的呢

**Comment by sunshine-ssl** [comment]
我训练的ODS结果也只到0.78，请问您的问题解决了吗

**Comment by wangsun1996** [comment]
同学您好，我在训练的时候loss变化很大，并且最后两层出来的图都是全黑的。我想要用RCF模型进行一些图像边缘的检测，请问您方便给我分享一下您训练好的模型文件吗？

**Comment by MeLonJ10** [comment]
> 同学您好，我在训练的时候loss变化很大，并且最后两层出来的图都是全黑的。我想要用RCF模型进行一些图像边缘的检测，请问您方便给我分享一下您训练好的模型文件吗？

请问您知道是什么原因导致最后两层出来的结果是全黑的吗？

**Comment by cainiaoqiuzhu** [comment]
> 我训练的ODS结果也只到0.78，请问您的问题解决了吗

同学你好，请问你计算ODS是用matlab版本的评价函数吗？还是说你有其他的评价函数呢？

**Comment by AishuaiYao** [comment]
> @aobannong
> My result is stable.
> Do you use voc+BSDS500 dataset?
> Do you use data augmentation?



> @aobannong
> My result is stable.
> Do you use voc+BSDS500 dataset?
> Do you use data augmentation?

嗨，同学你好，我最近也在跑这个代码，但是感觉结果不是很正常，能否和您请教一下处理过程呢？

**Comment by 2916850681** [comment]
> 我训练的ODS结果也只到0.78，请问您的问题解决了吗

我的精度也达不到论文给的啊T_T,您精度问题解决了吗？

**Comment by AishuaiYao** [comment]
> > 我训练的ODS结果也只到0.78，请问您的问题解决了吗
> 
> 我的精度也达不到论文给的啊T_T,您精度问题解决了吗？

额，这个ODS指标怎么测的，我都不没找到呢。不过我现在的模型输出结果图看起来比较接近论文里demo的样子了，并且已经够用了

**Comment by 2916850681** [comment]
也没有，但是比你高一点，0.792



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 11, 2021 16:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [meteorshowers/RCF-pytorch] Can't reproduce the report results (#37)




   
我训练的ODS结果也只到0.78，请问您的问题解决了吗
  
我的精度也达不到论文给的啊T_T,您精度问题解决了吗？
  
额，这个ODS指标怎么测的，我都不没找到呢。不过我现在的模型输出结果图看起来比较接近论文里demo的样子了，并且已经够用了
