### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by StephenZhao1** [meteorshowers/RCF-pytorch#58]
1. first of all, I train your model on sklarge datasets and runs successfully.
2. I create my own datasets and train the same model with same process, cuda out of memory happens.
I find that sklarge image size is not very big, image size of my datasets is more bigger,maybe that is the cause, how can I optimize the model? My gpu memory is 8GB.

**Comment by CodeCat110** [comment]
https://blog.csdn.net/Together_CZ/article/details/126545991
